"project_id": "603693"
"api_token_env": "HOTELISTAN_CROWDIN_TOKEN"
"base_url": "https://api.crowdin.com"
"base_path": "./i18n/"
"preserve_hierarchy": true

files: [
  {
    "source": "implant-en.php",
    "dest": "Nova Vita-implant.php",
    "translation": "/Nova Vita-implant-%two_letters_code%.php",
    "translation_replace": { "Nova Vita-": "" },
    "excluded_target_languages": [ "es-ES" ],

    #
    # The parameter "update_option" is optional.
    # If it is not set, the translations for changed strings will be removed.
    # Use to fix typos and for minor changes in the source strings
    # e.g. "update_as_unapproved" or "update_without_changes"
    # "update_option": "update_without_changes",
    #
  }
]